#SQL:

host: localhost
port: 3306
database: "creatorsdb"
username: root
password: root

table: "creators"

# If true, queries will be excecuted every query_cooldown seconds.
# If false, queries will be excecuted only when the data is needed AND
# time indicated by query_cooldown has not elapsed.
# If query_regularly is false, and query_cooldown is zero or negative,
# queries will be only excecuted excactly every time the data is needed.
query_regularly: true
# time in ticks
query_cooldown: 200
# Only the data of the first local_cache creators by subscriber count will be continually stored locally. All creators that don't fit in will only be fetched from the database if necessary.
local_cache: 10000

extra_query_size: 0

# If a query fails, this many milliseconds will be spent before attempting again.
retry_cooldown: 0
# The query will be tried this many times before returning back to normal schedule.
query_retries: 2

# Verbose logging
logging: true


#Youtube API-key

youtube_apikey: AIzaSyAHF23xweo41nh8CzKYkKLmBzaSrFxlfNk