
# SQL driver class name. If you are using MySql, it is com.mysql.jdbc.Driver
sql_driver: com.mysql.jdbc.Driver

# URL of your SQL database
# Example: jdbc:mysql://localhost:3306/creatorsdb"
url: "jdbc:mysql://localhost:3306/creatorsdb"

# Username and password on the database

username: root
password: root

# What table should contain the data used by this plugin
table: "creators"

# Time between queries to refresh the local cache, in ticks. Set to -1 if you wish to query at startup.
query_cooldown: 12000
# Only the data of the first local_cache creators by subscriber count will be stored locally.
local_cache: 10000

# The query will be tried this many times before returning back to normal schedule.
query_retries: 2

# Table maintenance (updating subscriber counts, removing entries with non-exsisting channels)
# Cooldown in ticks, set to -1 if you wish to do maintenance only on startup.
maintenance_cooldown: 72000


# Youtube API-key. Required for checking channel validity.

youtube_apikey: AIzaSyAHF23xweo41nh8CzKYkKLmBzaSrFxlfNk

# Number of slots in the inventory GUI. Must be a multiple of 9, only 27 and 54 have been proven stable.

gui_size: 54