name: Creators
version: ${project.version}
main: me.george0030.creators.Creators
api-version: 1.16
commands:
  creators:
    description: List YouTube creators that play on this server
    permission: creators.view
    permission-message: You do not have permission!
    usage: /creators